algorithm: modis
amp: true
batch_size: 16
clip: 0.0
crop_ratio: 0.875
data_dir: your_save_dir/USB/data
dataset: stl10
dist_backend: nccl
dist_url: tcp://127.0.0.1:10016
ema_m: 0.0
epoch: 5
eval_batch_size: 250
gpu: 0
img_size: 96
layer_decay: 0.5
load_path: your_save_dir/USB/saved_models/two_phase/supervised/stl10_100/record_epoch2/latest_model.pth
lr: 0.0001
momentum: 0.9
multiprocessing_distributed: false
net: vit_base_patch16_96
net_from_name: false
new_sample_strategy: true
num_classes: 10
num_labels: 100
num_train_iter: 2000
num_workers: 4
optim: AdamW
overwrite: true
p_cutoff: 0.95
pretrain_path: your_save_dir/USB/pretrain_ckpt/mae_pretrain_vit_base.pth
rank: 0
resume: true
resume_all: true
save_dir: your_save_dir/USB/saved_models/two_phase/modis/stl10_100
save_name: tp_start_5
seed: 0
tp_epoch: 4
tp_gap: 100000
tp_info_path: your_save_dir/USB/saved_models/two_phase/supervised/stl10_100/record_epoch2/tp_latest_model.pth
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
unsup_warm_up: 0.4
uratio: 1
use_cat: true
use_pretrain: true
use_tensorboard: false
use_tp: true
use_wandb: false
weight_decay: 0.0005
world_size: 1
