algorithm: supervised
save_dir: your_root_path/USB/saved_models/two_phase/supervised/cifar_1000
save_name: embedding
resume: False
load_path: your_root_path/USB/saved_models/two_phase/supervised/cifar_1000/embedding/latest_model.pth
overwrite: True
use_tensorboard: False
use_wandb: False

epoch: 5
num_train_iter: 2000
batch_size: 250
eval_batch_size: 1000

num_labels: 10000
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: True
clip: 0.0
use_cat: True
net: vit_small_patch2_32
net_from_name: False
data_dir: your_root_path/USB/data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10021
dist_backend: nccl
gpu: 2
use_pretrain: True
pretrain_path: your_root_path/USB/pretrain_ckpt/vit_small_patch2_32_mlp_im_1k_32.pth

new_sample_strategy: True
use_tp: True
tp_gap: -1