algorithm: pseudolabel
save_dir: /mnt/bn/liyullm2/USB/saved_models/usb_cv/pseudolabel/
save_name: optuna
resume: True
is_mini_data: False
load_path: /mnt/bn/liyullm2/USB/saved_models/usb_cv/pseudolabel/optuna/latest_model.pth
overwrite: True
use_tensorboard: False
use_wandb: False
epoch: 10
num_train_iter: 250
num_log_iter: 5
tp_gap: 25
num_eval_iter: 25
batch_size: 250
eval_batch_size: 1000
num_warmup_iter: 10
num_labels: 200
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: True
clip: 0.0
use_cat: True
net: vit_small_patch2_32
net_from_name: False
data_dir: /mnt/bn/liyullm2/USB/data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: /mnt/bn/liyullm2/USB/pretrain_ckpt/vit_small_patch2_32_mlp_im_1k_32.pth

use_tp: True
tp_epoch: 5
new_sample_strategy: True