algorithm: ups
amp: true
batch_size: 8
clip: 0.0
crop_ratio: 0.875
data_dir: your_save_dir/USB/data
dataset: semi_aves
dist_backend: nccl
dist_url: tcp://127.0.0.1:10016
ema_m: 0.0
epoch: 10
eval_batch_size: 250
gpu: 0
img_size: 32
layer_decay: 0.65
load_path: your_save_dir/USB/saved_models/two_phase/ups/semi_aves_3959/record_epoch4/latest_model.pth
lr: 0.001
momentum: 0.9
multiprocessing_distributed: false
net: vit_small_patch2_32
net_from_name: false
new_sample_strategy: true
num_classes: 200
num_labels: 3959
num_train_iter: 2000
num_workers: 2
optim: AdamW
overwrite: true
p_cutoff: 0.95
pretrain_path: your_save_dir/USB/pretrain_ckpt/vit_small_patch2_32_mlp_im_1k_32.pth
rank: 0
resume: true
resume_all: true
save_dir: your_save_dir/USB/saved_models/two_phase/ups/semi_aves_3959
save_name: tp_start_4
seed: 0
tp_epoch: 4
tp_gap: 100000
tp_info_path: your_save_dir/USB/saved_models/two_phase/ups/semi_aves_3959/record_epoch4/tp_latest_model.pth
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
unsup_warm_up: 0.4
uratio: 1
use_cat: true
use_pretrain: true
use_tensorboard: false
use_tp: true
use_wandb: false
weight_decay: 0.0005
world_size: 1
