algorithm: ups
amp: true
batch_size: 8
clip: 0.0
crop_ratio: 0.875
data_dir: your_save_dir/USB/data
dataset: stl10
dist_backend: nccl
dist_url: tcp://127.0.0.1:10016
ema_m: 0.0
epoch: 4
eval_batch_size: 250
gpu: 0
img_size: 96
layer_decay: 0.5
load_path: your_save_dir/USB/saved_models/two_phase/ups/stl10_40/tp_record/latest_model.pth
lr: 0.0001
momentum: 0.9
multiprocessing_distributed: false
net: vit_base_patch16_96
net_from_name: false
new_sample_strategy: true
num_classes: 10
num_labels: 40
num_train_iter: 2000
num_workers: 1
optim: AdamW
overwrite: false
p_cutoff: 0.95
pretrain_path: your_save_dir/USB/pretrain_ckpt/mae_pretrain_vit_base.pth
rank: 0
resume: false
save_dir: your_save_dir/USB/saved_models/two_phase/ups/stl10_40
save_name: record_epoch4
seed: 0
tp_gap: -1
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
unsup_warm_up: 0.4
uratio: 1
use_cat: true
use_pretrain: true
use_tensorboard: false
use_tp: true
use_wandb: false
weight_decay: 0.0005
world_size: 1
